version: "3.7"

volumes:
  wordpress_v:
    driver: local
    driver_opts:
      type: none
      device: /home/aguediri/data/wordpress
      o: bind
  mariadb_v:
    driver: local
    driver_opts:
      type: none
      device: /home/aguediri/data/mariadb
      o: bind

services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_v:/var/lib/mysql
      - ./db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
    networks:
      - inception

  wordpress:
      build: requirements/wordpress/.
      image: wordpress
      container_name: wordpress
      env_file:
        - .env
      ports:
        - "9000:9000"
      volumes:
        - wordpress_v:/var/www/html
      networks:
        - inception
      depends_on:
        - mariadb

  nginx:
    build: requirements/nginx/.
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_v:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge
